# Generated by Django 5.2.9 on 2025-12-27 16:29

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to='tarea_planner.user')),
            ],
        ),
    ]
